// <auto-generated />
namespace Personeel.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createPersoneelDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createPersoneelDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202203291312456_createPersoneelDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
